### ISSUE TITLE
Failed to connect 

### ISSUE THREAD

**Issue by UnknownNull** [LuciaDX/VoiceCraftPM#2]
[Server thread/ERROR]: Failed to connect to localhost:12345
and
[Server thread/ERROR]: Failed to connect to localhost:9050

config:

```
Ip: "localhost"
Port: "9050"
LoginKey: ""
Settings:
  ProximityDistance: 30
  ProximityToggle: true
```
